// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently, but
// are changed infrequently

#pragma once

#pragma warning(disable:4995)
#include "../../xrEngine/stdafx.h"
#pragma warning(disable:4995)
#include <d3dx9.h>
#pragma warning(default:4995)
#pragma warning(disable:4714)
#pragma warning( 4 : 4018 )
#pragma warning( 4 : 4244 )
#pragma warning(disable:4237)

#include <d3d12.h>
#include <d3dcompiler.h>
#include <dxgi1_6.h>

// Bridge Windows SDK enum names to DirectX-Headers names
#ifndef D3D12_PRIMITIVE_TOPOLOGY_UNDEFINED
#define D3D12_PRIMITIVE_TOPOLOGY_UNDEFINED D3D_PRIMITIVE_TOPOLOGY_UNDEFINED
#define D3D12_PRIMITIVE_TOPOLOGY_POINT_LIST D3D_PRIMITIVE_TOPOLOGY_POINTLIST
#define D3D12_PRIMITIVE_TOPOLOGY_LINE_LIST D3D_PRIMITIVE_TOPOLOGY_LINELIST
#define D3D12_PRIMITIVE_TOPOLOGY_LINE_STRIP D3D_PRIMITIVE_TOPOLOGY_LINESTRIP
#define D3D12_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
#define D3D12_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
#define D3D12_PRIMITIVE_TOPOLOGY_LINE_LIST_ADJ D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ
#define D3D12_PRIMITIVE_TOPOLOGY_LINE_STRIP_ADJ D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ
#define D3D12_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_ADJ D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ
#define D3D12_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_ADJ D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
#define D3D12_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST
#define D3D12_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST
#endif

#include "../xrRender/xrD3DDefs.h"

#define		R_R1	1
#define		R_R2	2
#define		R_R3	3
#define		R_R4	4
#define		R_R5	5
#define		RENDER	R_R5

#include "../../xrParticles/psystem.h"

#include "../xrRender/HW.h"
#include "../xrRender/Shader.h"
#include "../xrRender/R_Backend.h"
#include "../xrRender/R_Backend_Runtime.h"

#include "../xrRender/resourcemanager.h"

#include "../../xrEngine/vis_common.h"
#include "../../xrEngine/render.h"
#include "../../xrEngine/_d3d_extensions.h"
#include "../../xrEngine/igame_level.h"
#include "../xrRender/blenders\blender.h"
#include "../xrRender/blenders\blender_clsid.h"
#include "../xrRender/xrRender_console.h"
#include "r5.h"
